### ISSUE TITLE
Missing xbox controller functionality after update to Kodi v17 from v16

### ISSUE THREAD

**Issue by Juppstein** [mdeguzis/SteamOS-Tools#162]
#### Your system information

* Steam client version: 1486690646
* SteamOS version: 2.0 u 2.110
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
After update from v16 to v17 Xbox 360 wireless controller stopped working in Kodi, but continues to work in BPM and games. Peripheral category in settings/addons is missing as well.

#### Steps for reproducing this issue:

1. Update from Kodi v16 to v17 on SteamOS

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by mdeguzis** [comment]
I will be away this weekend, returning Sunday evening, ~20:00 UTC-5. Sorry for the delay.

**Comment by mdeguzis** [comment]
Isn't this solved by the inputstream package you already requested?

**Comment by Juppstein** [comment]
No, inputstream is for video playback. This here is for game controllers to control kodi

**Comment by mdeguzis** [comment]
hmm ok, well if you turn up any forum posts, let me know. I plan on testing this in the next few days.

**Comment by mdeguzis** [comment]
There is a package in the PPA called "kodi-peripheral-joystick - 1.2.0-3". I'll build it tonight. Give it a try tomorrow.

**Comment by mdeguzis** [comment]
Give me a bit of time on this one. Doesn't seem the packaging repo was updated for Kyrpton, and a diff on the debian folder from the PPA shows some new packages/changes. I am going to backup my old script that utilizes 'xbmc/tools/Linux/packaging/mk-debian-package.sh' upstream, and simply uses the debian/ folder like 98% of all my other packages. Downside is if an older build is requested, but I'll keep my fork of xbmc-packaging as a fall back.

Once I get that down, I can add missing packages, like the joystick peripherals package.

**Comment by Juppstein** [comment]
Fine, I already saw that the package was missing in the repo so I thought something might have come up.

**Comment by mdeguzis** [comment]
Got the revised build method for Kodi fixed up today. I should have a new version of Kodi out tonight. I'll work on getting the other packages added that are new as well. I will add the joystick package as a dependency if this solves your issue. If it does, i'll add that to debian/control when I push out the other missing packages.

Check tomorrow for a new Kodi version and the joystick package mentioned above. If I somehow get all the packaging done tonight, i'll push those, but not the debian/control change.

**Comment by mdeguzis** [comment]
All missing packages from the stable PPA are up. That means visualizations, inputstream packages, and all audio packages.

**Comment by Juppstein** [comment]
Joystick/controller works now and I got the new Kodi version installed  but you might have broken the PVR addons in the process. It now asks for tvheadend-hts version 3.4.18 while before it was 3.4.17.

**Comment by mdeguzis** [comment]
Great, i'll add that as a dependency to Kodi. As far as the PVR addon, I only have 3.4.17, and that is all that is available as a tag. I've been using the "Krypton" branch when I can, or, when that is absent, the latest tag. Previous to this, it was the branch "Jarvis" I used. If you update the addon, will it work? Or, is it preventing you from doing things? I can look over the addon build scripts tonight if you continue to have issues.

**Comment by Juppstein** [comment]
I am not sure what new version you have compiled of Kodi. But somehow some of the pvr addon that did worked yesterday fails to work today with this version of Kodi. The PVR addon now seems to have a version mismatch where Kodi asks for a newer version than the one that is installed/available in the repo. 

Here is a snipped from my logfile:

.......
```

18:21:22.068 T:139703169132608   ERROR: ADDON: Could not locate inputstream.adaptive.so.1.0.6
18:21:22.087 T:139702689847040  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
```

.....

```
18:21:30.342 T:139699926537984  NOTICE: [xbmcswift2] Request for "/createFollowingList/" matches rule for function "createFoll
owingList"
18:22:02.254 T:139703169132608   ERROR: ADDON: Could not locate pvr.hts.so.3.4.18
18:22:02.254 T:139703169132608   ERROR: UpdateAddons - failed to create add-on Tvheadend HTSP Client, status = 6
```

So, the pvr addon in Kodi has its version listed as 3.4.18, the one in the repo is 3.4.17 .  Also the inputstream-adaptive addon seems to not work as well now. I had to disable it in Kodi/Youtube Addon.

As far as I understand it the pvr addons are only visible in Kodi, and you can only activate them, if you have installed the respective package from a repo. So the PVR addons work different to a standard addon. Which makes it look strange to me that the version number in Kodi is different to the version number of the installed deb package

```
 lalala:~# aptitude versions kodi-pvr-hts
 Package kodi-pvr-hts:
 i   3.4.17+git+bsos1                                                     <NULL>                                           120
```

**Comment by mdeguzis** [comment]
Ah... so what I likely have to do, is rebuild the pvr addons with this new version.. I'll update the PVR addons again tonight or tomorrow after checking some things. The PVR addons require kodi-pvr-dev, libkodiplatform-dev, and kodi-addon-dev. Sorry for the trouble.

**Comment by Juppstein** [comment]
No biggie. I've installed an IP-TV addon in the meantime to bridge the gap.

**Comment by mdeguzis** [comment]
Can you list me the steps you used? Please list the version of any applicable packages, including kodi. I'll make sure I can reproduce this so I know it is fixed.

**Comment by Juppstein** [comment]
Back when the PVR addons were still missing in the repo and I updated from Kodi 16 to 17 the old PVR addon version for Jarvis was 2.2.14 but unfortunately I don't know which Kodi was asking for after it got updated from Jarvis to Krypton. But it was the same end result, an error message that the PVR addon was not loaded and the Live-TV icon was gone from the menu.

Yesterday I had the kodi version before the one you have updated today. I updated the repo and downloaded/installed the tvheadend addon for kodi (v 3.4.17) via apt-get install kodi-pvr-tvheadend
```
Package kodi-pvr-hts:
i   3.4.17+git+bsos1 
```
Since I had this type of addon in use before, it was already configured and activated in Kodi so when I started Kodi the PVR addon started without issues and I was able to watch TV. 

Today I have updated to the new Kodi version from the repo 
```
Package kodi:
i   2:17.0+git20170222+bsos-3 
```
The moment I started Kodi I got the error message that the PVR addon was not able to load properly and the Live-TV icon was not visible anymore. I then went to Settings - Addons and tried to activate the addon manuall, which failed.

```
18:22:02.254 T:139703169132608   ERROR: ADDON: Could not locate pvr.hts.so.3.4.18
18:22:02.254 T:139703169132608   ERROR: UpdateAddons - failed to create add-on Tvheadend HTSP Client, status = 6
```
The version mentioned Kodi for the pvr addon settings is 3.4.18, the installed version is 3.4.17. Which would explain the problems loading the plugin.

I hope this makes sense and help a bit.

**Comment by mdeguzis** [comment]
It does, i'll have more time to investigate tomorrow. I know the addon's store the versioning in XML, so i'll check out the code as well upstream.

**Comment by mdeguzis** [comment]
Ahead of actual testing I checked out the libs the package builds (I don't maintain the packaging files btw).
```
root@archboxmtd:/build/kodi-pvr-hts-3.4.17+git+bsos1# find . -name "*.so"
./debian/tmp/usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so
./debian/kodi-pvr-hts/usr/share/kodi/addons/pvr.hts/pvr.hts.so
./obj-x86_64-linux-gnu/pvr.hts.so

root@archboxmtd:/build/kodi-pvr-hts-3.4.17+git+bsos1# file ./obj-x86_64-linux-gnu/pvr.hts.so
./obj-x86_64-linux-gnu/pvr.hts.so: symbolic link to pvr.hts.so.17.0
```

I also unpacked the deb file from the PPA:

```
mikeyd@archboxmtd pvr-addons $ file ./usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so
./usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so: symbolic link to pvr.hts.so.17.0
```

Not sure where that versioning is coming from, unless it tries to pick up something based on the package. I'm not yet convinced it is simply from me building a package. I do not host the debian files. I might suspect that it is because I updated the Kodi build. I'll build the addons again and see how it fares.

**Comment by Juppstein** [comment]
Saw that a new update is up and PVR seems to work now. It now lists 3.4.19 in Kodi under PVR addons and 3.4.17 for the package in SteamOS. But it works. 
```
Package kodi-pvr-hts:
i   3.4.17+git+bsos2  
Package kodi-pvr-hts-dbg:
p   3.4.17+git+bsos2    
```

Though I get an issue now on loading the inputstream-adaptive package

`10:29:44.611 T:139799683094592   ERROR: ADDON: Could not locate inputstream.adaptive.so.1.0.6`

And when having it activated in the Youtube addon, videos above 720p will not load anymore

```
10:32:14.962 T:139798870292224  NOTICE: [plugin.video.youtube] Running: YouTube (5.3.10) on Krypton (Kodi-17.0) with Python 2.7.9
10:32:21.074 T:139798870292224  NOTICE: Previous line repeats 2 times.
10:32:21.074 T:139798870292224  NOTICE: [plugin.video.youtube] Unable to use mpeg-dash for T2g8pNujrBk, unable to decipher signature. Attempting fallback play method...
10:32:21.959 T:139799195416320  NOTICE: [plugin.video.youtube] Running: YouTube (5.3.10) on Krypton (Kodi-17.0) with Python 2.7.9
10:32:22.061 T:139799683094592  NOTICE: VideoPlayer: Opening: https://r1---sn-ph2gvf5gx-haie.googlevideo.com/videoplayback?dur=916.747&ei=pf2vWO3zCoj1WMKml-AC&beids=[9452307]&requiressl=yes&pl=17&sparams=dur,ei,id,initcwndbps,ip,ipbits,i
tag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&id=o-ACMVSV9YOtMklJKlBTtBZXqAkBQvawpnKY4G1blbOJJs&ms=au&mt=1487928624&mv=m&initcwndbps=2657500&mm=31&mn=sn-ph2gvf5gx-haie&ip=87.102.180.177&key=yt6&source=youtube&rateby
pass=yes&lmt=1486547645979809&upn=lq3oDThfZKg&expire=1487950341&ipbits=0&itag=22&mime=video/mp4&signature=A2949F4FE64052C8FF7EBE39A763B218065775B8.068B534789726D1316D9EE7161CE6485CDD14233
```

**Comment by mdeguzis** [comment]
Wait until a few hours from now. The install path for the PVR libs was wrong. I'll look at input stream as well.

**Comment by Juppstein** [comment]
After todays update, the PVR addon stopped working again:

Installed pvr addon package
```
Package kodi-pvr-tvheadend-hts:
i   3.4.17+git+bsos3   
```
Error message from Kodi when it tries to load it
```
09:03:34.854 T:140582479788096   ERROR: ADDON: Could not locate pvr.hts.so.3.4.19
09:03:34.854 T:140582479788096   ERROR: UpdateAddons - failed to create add-on Tvheadend HTSP Client, status = 6
```

**Comment by mdeguzis** [comment]
I can tell you the install is the right path where he libs are going. I need to see if Kodi is expecting the wrong version/lib or if the add-on is. For this add-on only, I am going to use the Krypton branch.

**Comment by Juppstein** [comment]
Endless fun :D

**Comment by mdeguzis** [comment]
I did post a thread [here](http://forum.kodi.tv/showthread.php?tid=308134), maybe get some answers.

**Comment by wsnipex** [comment]
3.4.19 is the correct version for pvr-hts Krypton, see https://github.com/kodi-pvr/pvr.hts/blob/Krypton/pvr.hts/addon.xml.in#L4
Since kodi is looking for this version, it has successfully parsed this addon.xml (/usr/share/kodi/addons/pvr.hts), it is probably that the addon is build from the correct branch and should work if the shared lib had the correct version. Can you try to rename /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.x.y.z to /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.19?
If that works the is some bug in the packaging script

**Comment by wsnipex** [comment]
https://github.com/mdeguzis/LibreGeek-Packaging/blob/steamos/kodi/pvr-addons/build-pvr-hts.sh#L62

**Comment by mdeguzis** [comment]
I'll bump my package version and check the resultant like @wsnipex. If that is the case, and works. I'll always source the version from the XML code. Thank you for your help.

**Comment by mdeguzis** [comment]
@wsnipex, I sourced the version from the XML file in my build script, but the resultant libs are still 17.0

```
root@archboxmtd:/build/kodi-pvr-hts-3.4.19+git+bsos1# file ./debian/tmp/usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so
./debian/tmp/usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so: symbolic link to pvr.hts.so.17.0
```

Is this right? Shouldn't it be 19.0?

**Comment by mdeguzis** [comment]
Ok I see, the installs for the pvr's should follow this format so the multi-arch path is retained.

```
usr/lib/*/kodi/addons/pvr.hts/pvr.hts.so*
usr/share/kodi/addons/pvr.hts
```

not

```
usr/lib/*/addons/pvr.hts/pvr.hts.so* usr/lib/kodi/addons/pvr.hts
usr/share/kodi/addons/pvr.hts

```

**Comment by mdeguzis** [comment]
@Juppstein , new packages uploaded. Please upgrade and retest.

**Comment by Juppstein** [comment]
Looks good, PVR addon loads and is functional without throwing any errors in the log.

**Comment by mdeguzis** [comment]
sweet deal. Open a new issue if you continue to have any problems.
